test4

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -17,7 +17,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Install pnpm
-        uses: pnpm/action-setup@v4
+        uses: pnpm/action-setup@v2
         with:
           version: 8
 
@@ -32,8 +32,8 @@ jobs:
 
       - name: tsc & build
         run: |
-          pnpm -F assignment-6 tsc > tsc-output.log 2>&1
-          pnpm -F assignment-6 build > build-output.log 2>&1
+          pnpm --filter assignment-6 tsc > tsc-output.log 2>&1
+          pnpm --filter assignment-6 build > build-output.log 2>&1
 
       - name: Comment on PR
         if: failure()
@@ -41,6 +41,7 @@ jobs:
         with:
           github-token: ${{ secrets.TOKEN_FOR_CI }}
           script: |
+            const fs = require('fs');
             const tscLog = fs.readFileSync('tsc-output.log', 'utf8');
             const buildLog = fs.readFileSync('build-output.log', 'utf8');
             const body = `
@@ -68,7 +69,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Install pnpm
-        uses: pnpm/action-setup@v4
+        uses: pnpm/action-setup@v2
         with:
           version: 8
 
@@ -82,7 +83,7 @@ jobs:
         run: pnpm install
 
       - name: Lint
-        run: pnpm -F assignment-6 lint > lint-output.log 2>&1
+        run: pnpm --filter assignment-6 lint > lint-output.log 2>&1
 
       - name: Comment on PR
         if: failure()
@@ -90,6 +91,7 @@ jobs:
         with:
           github-token: ${{ secrets.TOKEN_FOR_CI }}
           script: |
+            const fs = require('fs');
             const lintLog = fs.readFileSync('lint-output.log', 'utf8');
             const body = `
               **ESLint Logs**
@@ -111,7 +113,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Install pnpm
-        uses: pnpm/action-setup@v4
+        uses: pnpm/action-setup@v2
         with:
           version: 8
 
@@ -125,7 +127,7 @@ jobs:
         run: pnpm install
 
       - name: Create test coverage
-        run: pnpm -F assignment-6 test:coverage > test-output.log 2>&1
+        run: pnpm --filter assignment-6 test:coverage > test-output.log 2>&1
 
       - name: Comment on PR
         if: failure()
@@ -133,6 +135,7 @@ jobs:
         with:
           github-token: ${{ secrets.TOKEN_FOR_CI }}
           script: |
+            const fs = require('fs');
             const testLog = fs.readFileSync('test-output.log', 'utf8');
             const body = `
               **Test Coverage Logs**
@@ -162,7 +165,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Install pnpm
-        uses: pnpm/action-setup@v4
+        uses: pnpm/action-setup@v2
         with:
           version: 8
 
@@ -176,14 +179,14 @@ jobs:
         run: pnpm install
       
       - name: Build
-        run: pnpm -F assignment-6 build
+        run: pnpm --filter assignment-6 build
 
       - name: Run Lighthouse ci
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
         run: |
           pnpm install -g @lhci/cli
-          pnpm -F assignment-6 lighthouse > lighthouse-output.log 2>&1 || echo "Fail to Run Lighthouse CI"
+          pnpm --filter assignment-6 lighthouse > lighthouse-output.log 2>&1 || echo "Fail to Run Lighthouse CI"
 
       - name: Comment Lighthouse results
         if: always()
