test1

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -6,7 +6,6 @@ on:
       - synchronize
       - opened
       - reopened
-
     paths:
       - 'packages/assignment-6/**'
 
@@ -39,7 +38,7 @@ jobs:
         id: tsc
 
       - name: Build Project
-        run: pnpm -F assignment-6 build > error.log 2>&1
+        run: pnpm -F assignment-6 build > build-error.log 2>&1
         id: build
 
       - name: Check for errors
@@ -90,28 +89,28 @@ jobs:
 
       - name: Post ESLint report as comment
         if: failure()
-        uses: actions/github-script@v6.4.0
+        uses: actions/github-script@v7
         with:
           github-token: ${{ secrets.TOKEN_FOR_CI }}
           script: |
-            const fs = require('fs')
-            const report = fs.readFileSync('packages/assignment-6/.eslintrc.cjs', 'utf8')
-            const message = `## ESLint Results\n\n${report}`
+            const fs = require('fs');
+            const report = fs.readFileSync('lint_output.log', 'utf8');
+            const message = `## ESLint Results\n\n${report}`;
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: message            
+              body: message
             })
 
   test:
     runs-on: ubuntu-latest
     steps:
-      - name: Check out
+      - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@v2
+      - name: Setup pnpm
+        uses: pnpm/action-setup@v4
         with:
           version: 8
 
@@ -125,24 +124,39 @@ jobs:
         run: pnpm install
 
       - name: Create test coverage
-        run: pnpm --filter assignment-6 test:coverage
+        run: pnpm -F assignment-6 test:coverage > test_output.log 2>&1
+
+      - name: Post test coverage report as comment
+        if: failure()
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ secrets.TOKEN_FOR_CI }}
+          script: |
+            const fs = require('fs');
+            const report = fs.readFileSync('test_output.log', 'utf8');
+            const message = `## Test Coverage Results\n\n${report}`;
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: message
+            })
 
       - name: Report coverage
-        if: always()
         uses: davelosert/vitest-coverage-report-action@v2
         with:
           json-summary-path: packages/assignment-6/coverage/coverage-summary.json
           json-final-path: packages/assignment-6/coverage/coverage-final.json
           github-token: ${{ secrets.TOKEN_FOR_CI }}
-              
+
   lighthouse:
     runs-on: ubuntu-latest
     steps:
-      - name: Check out
+      - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@v2
+      - name: Setup pnpm
+        uses: pnpm/action-setup@v4
         with:
           version: 8
 
@@ -156,42 +170,34 @@ jobs:
         run: pnpm install
 
       - name: Build
-        run: pnpm --filter assignment-6 build
+        run: pnpm -F assignment-6 build
 
-      - name: Run Lighthouse ci
+      - name: Run Lighthouse CI
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
         run: |
           pnpm install -g @lhci/cli
-          pnpm --filter assignment-6 lighthouse || echo "Fail to Run Lighthouse CI"
-      - name: Comment Lighthouse comment
-        if: always()
+          pnpm --filter assignment-6 lighthouse > lighthouse_output.log 2>&1 || echo "Fail to Run Lighthouse CI"
+
+      - name: Post Lighthouse CI report as comment
+        if: failure()
         uses: actions/github-script@v7
         with:
           github-token: ${{ secrets.TOKEN_FOR_CI }}
           script: |
             const fs = require('fs');
-            const results = JSON.parse(fs.readFileSync('packages/assignment-6/lhci_reports/manifest.json', 'utf8'));
-            let comment = "# Lighthouse 성능 측정 결과\n| 카테고리 | 점수 |\n| :---: | :---: |";
-            results.forEach((result) => {
-              const { summary } = result;
-              Object.entries(summary).forEach(([key, value]) => {
-                const capitalizedKey = key.charAt(0).toUpperCase() + key.slice(1);
-                const score = (value * 100);
-                comment += `\n| ${capitalizedKey} | ${score}% |`;
-              });
-            })
+            const results = fs.readFileSync('lighthouse_output.log', 'utf8');
+            const message = `## Lighthouse CI Results\n\n${results}`;
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: comment
-            });
+              body: message
+            })
 
   assign_reviewer:
     runs-on: ubuntu-latest
     if: github.event.action == 'opened'
-
     steps:
       - uses: actions/checkout@v4
 
@@ -201,14 +207,15 @@ jobs:
         run: |
           gh api repos/${{ github.repository }}/collaborators/tsihnavy99 -X PUT -f permission=push
           gh api repos/${{ github.repository }}/collaborators/steve-shim -X PUT -f permission=push
-      - name: Pick a teammate randomly & select him as reviewer & request review
-        uses: actions/github-script@v6
+
+      - name: Pick a teammate randomly & select them as reviewer & request review
+        uses: actions/github-script@v7
         with:
-          github-token: ${{secrets.TOKEN_FOR_CI}}
+          github-token: ${{ secrets.TOKEN_FOR_CI }}
           script: |
             const myTeammates = [
-            {name:'형예은', github: 'tsihnavy99'},
-            {name:'심승혁', github: 'steve-shim'}
+              {name:'형예은', github: 'tsihnavy99'},
+              {name:'심승혁', github: 'steve-shim'}
             ];
             const randomIndex = Math.round(Math.random());
             const reviewerName = myTeammates[randomIndex].name;
@@ -217,14 +224,14 @@ jobs:
             @${reviewerGithub} ${reviewerName}님, 리뷰를 부탁드립니다.
             `;
             await github.rest.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: comment
-            })
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: comment
+            });
             await github.rest.pulls.requestReviewers({
               pull_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               reviewers: [reviewerGithub]
-            })
+            });
