요구사항5: job4: lighthouse ci 를 실행하고, 실행 결과를 코멘트에 남긴다.

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -138,8 +138,55 @@ jobs:
   lighthouse:
     runs-on: ubuntu-latest
     steps:
-      - name: job4 구현
-        run: echo "job4의 내용을 구현해주세요"
+      - name: Check out
+        uses: actions/checkout@v4
+
+      - name: Install pnpm
+        uses: pnpm/action-setup@v2
+        with:
+          version: 8
+
+      - name: Setup Node.js environment
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "pnpm"
+
+      - name: Install dependencies
+        run: pnpm install
+
+      - name: Build
+        run: pnpm --filter assignment-6 build
+
+      - name: Run Lighthouse ci
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+        run: |
+          pnpm install -g @lhci/cli
+          pnpm --filter assignment-6 lighthouse || echo "Fail to Run Lighthouse CI"
+      - name: Comment Lighthouse comment
+        if: always()
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ secrets.TOKEN_FOR_CI }}
+          script: |
+            const fs = require('fs');
+            const results = JSON.parse(fs.readFileSync('packages/assignment-6/lhci_reports/manifest.json', 'utf8'));
+            let comment = "# Lighthouse 성능 측정 결과\n| 카테고리 | 점수 |\n| :---: | :---: |";
+            results.forEach((result) => {
+              const { summary } = result;
+              Object.entries(summary).forEach(([key, value]) => {
+                const capitalizedKey = key.charAt(0).toUpperCase() + key.slice(1);
+                const score = (value * 100);
+                comment += `\n| ${capitalizedKey} | ${score}% |`;
+              });
+            })
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: comment
+            });
 
   assign_reviewer:
     runs-on: ubuntu-latest
